app/views/main_views.py
from flask import Blueprint, redirect, render_template, current_app, request, url_for, flash
from flask_user import current_user, login_required, roles_required
from app import db
from app.models.user_models import UserProfileForm
from app.securities.holdings import Security_Data
from app.securities.data import Position
import pandas
import os
from datetime import datetime
main_blueprint = Blueprint('main', __name__, template_folder='templates')


# The Home page is accessible to anyone
@main_blueprint.route('/')
def home_page():
    return render_template('main/home_page.html')

@main_blueprint.route('/about')
def about_page():
    return render_template('main/about.html')


@main_blueprint.route('/login', methods=['GET', 'POST'])
def sign_in_page():
    return render_template('main/user_login.html')


# The User page is accessible to authenticated users (users that have logged in)
@main_blueprint.route('/member', methods=['GET', 'POST'])
@login_required  # Limits access to authenticated users
def member_page():
    if request.method == "POST" and 'userport' in request.files:
        position = Position()
        email = current_user.email
        file = request.files['userport']
        file.save(os.path.join('app/static/portfolios', email))
        flash("File Saved!")
        return render_template('main/user_page.html')
    if request.method == "POST" and 'etradeport' in request.files:
        position = Position()
        email = current_user.email
        file = request.files['etradeport']
        file = position.get_etrade_data_from_file(file)
        file.to_csv(os.path.join('app/static/portfolios', email), encoding='utf-8', index=False)
        flash("File Saved!")
        return render_template('main/user_page.html')
    else:
        return render_template('main/user_page.html')


# The Admin page is accessible to users with the 'admin' role
@main_blueprint.route('/admin')
@roles_required('admin')  # Limits access to users with the 'admin' role
def admin_page():
    return render_template('main/admin_page.html')


@main_blueprint.route('/main/profile', methods=['GET', 'POST'])
@login_required
def user_profile_page():
    # Initialize form
    form = UserProfileForm(request.form, obj=current_user)

    # Process valid POST
    if request.method == 'POST' and form.validate():
        # Copy form fields to user_profile fields
        form.populate_obj(current_user)

        # Save user_profile
        db.session.commit()

        # Redirect to home page
        return redirect(url_for('main.home_page'))

    # Process GET or invalid POST
    return render_template('main/user_profile_page.html',
                           form=form)


@main_blueprint.route('/equity')
@login_required
def equity_page(equity_key):
    eqdb = current_app.config["eqdb"]
    equity = eqdb.get_equity(equity_key)
    return render_template("equity.html", equity=equity)


# @main_blueprint.route('/holdings', methods=['GET', 'POST'])
# @login_required
# def holdings_page():
#     secdb = Security_Data()
#     holdings = secdb.get_holdings('holdings2.csv')
#     data = secdb.get_data(holdings)
#     dataII = data.to_numpy()
#     secdb = secdb.seed_holdings(dataII)
#     if request.method == "GET":
#         securities = secdb.get_securities()
#         return render_template("main/holdings.html", securities=securities)
#     else:
#         form_security_keys = request.form.getlist("security_keys")
#         for form_security_key in form_security_keys:
#             secdb.delete_equity(int(form_security_key))
#         return redirect(url_for("holdings_page"))


@main_blueprint.route('/Portfolio', methods=['GET', 'POST'])
@login_required
def portfolio_page():
    if request.method == "GET":
        position = Position()
        csv = position.get_port_data()
        df = position.get_data_from_file(csv)
        holdings = position.get_holdings(df)
        return render_template("main/portfolio.html", tables=[
            holdings.to_html(header=True, index=False, na_rep="--", table_id="Portfolio",
                             columns=['Symbol', 'Option Underlier',
                                      'Option Type', 'Quantity', 'Strike Price', 'Expiration Date', 'Market Price',
                                      'Option Delta', 'Exposure'],
                             formatters={"Market Price": "${:,.2f}".format, "Option Delta": "{:.1%}".format,
                                         "Exposure": "{:,.0f}".format})])
    elif request.method == "POST":

        position = Position()
        email = current_user.email
        file = request.files['userport']
        file.save(os.path.join('app/static/portfolios', email))
        portfolio = 'app/static/portfolios/' + str(email)
        df = position.get_data_from_file(portfolio)
        holdings = position.get_holdings(df)
        return render_template("main/portfolio.html", tables=[
            holdings.to_html(header=True, index=False, na_rep="--", table_id="Portfolio",
                             columns=['Symbol', 'Option Underlier',
                                      'Option Type', 'Quantity', 'Strike Price', 'Expiration Date',
                                      'Market Price',
                                      'Option Delta', 'Exposure'],
                             formatters={"Market Price": "${:,.2f}".format, "Option Delta": "{:.1%}".format,
                                         "Exposure": "{:,.0f}".format})])

    else:
        flash("Something went wrong - you were redirected home!  Please try again.")
        return redirect(url_for("main.member_page"))


@main_blueprint.route('/Group', methods=['GET', 'POST'])
@login_required
# @csrf.exempt
def group_page():
    # if request.method == "GET":
    #     position = Position()
    #     ticker = "AAPL"
    #     csv = position.get_port_data()
    #     df = position.get_data_from_file(csv)
    #     df["Option Underlier"] = df.apply(lambda x: position.add_und(x["Type"], x["Option Underlier"], x["Symbol"]),
    #                                       axis=1)
    #     group = position.filter_holdings(df, ticker)
    #     group = position.get_holdings(group)
    #     group.loc["Total Exposure"] = group.sum(["Exposure"],axis =0)
    #     return render_template("main/group.html", tables=[
    #         group.to_html(header=True, index=False, na_rep="--", table_id="Portfolio",
    #                       columns=['Symbol', 'Option Underlier',
    #                                'Option Type', 'Quantity', 'Strike Price', 'Expiration Date', 'Market Price',
    #                                'Option Delta', 'Exposure'],
    #                       formatters={"Market Price": "${:,.2f}".format, "Option Delta": "{:.1%}".format,
    #                                   "Exposure": "{:,.0f}".format})])
    if request.method == "POST":
        position = Position()
        ticker = request.form.get('ticker').upper()
        csv = position.get_port_data()
        df = position.get_data_from_file(csv)
        group, deltas, vols = position.group_process(df, ticker)
        vol_exp = position.vols_process(vols)
        exposure = position.delta_process(deltas)
        return render_template("main/group.html", tables=[group, exposure, vol_exp], titles=['', 'Group Holdings', 'Equity Exposure', 'Volatility Exposure'])
    else:
        flash("Something went wrong - you were redirected home!  Please try again.")
        return redirect(url_for("main.member_page"))


@main_blueprint.route('/Sample2', methods=['GET', 'POST'])
def sample2_page():
    if request.method == "GET":
        position = Position()
        csv = "holdings2.csv"
        df = position.get_etrade_data_from_file(csv)
        sample2 = position.get_holdings(df)
        return render_template("main/sample2.html", tables=[
            sample2.to_html(header=True, index=False, na_rep="--", table_id="Portfolio",
                            columns=['Symbol', 'Option Underlier',
                                     'Option Type', 'Quantity', 'Strike Price', 'Expiration Date', 'Market Price',
                                     'Option Delta', 'Exposure'],
                            formatters={"Market Price": "${:,.2f}".format, "Option Delta": "{:.1%}".format,
                                        "Exposure": "{:,.0f}".format})])
    else:
        return redirect(url_for("main/home_page.html"))

@main_blueprint.route('/NewEquity', methods=['GET', 'POST'])
@login_required
# @csrf.exempt
def new_equity_page():
    # if request.method == "GET":
    #     position = Position()
    #     ticker = "FSLY"
    #     csv = position.get_port_data()
    #     df = position.get_data_from_file(csv)
    #     group = position.filter_holdings(df, ticker)
    #     group = position.get_holdings(group)
    #     group.loc["Total Exposure"] = group.sum(["Exposure"],axis =0)
    #     return render_template("main/group.html", tables=[
    #         group.to_html(header=True, index=False, na_rep="--", table_id="Portfolio",
    #                       columns=['Symbol', 'Option Underlier',
    #                                'Option Type', 'Quantity', 'Strike Price', 'Expiration Date', 'Market Price',
    #                                'Option Delta', 'Exposure'],
    #                       formatters={"Market Price": "${:,.2f}".format, "Option Delta": "{:.1%}".format,
    #                                   "Exposure": "{:,.0f}".format})])
    if request.method == "POST":
        position = Position()
        ticker = request.form.get('ticker').upper()
        quantity = request.form.get("quantity")
        quantity = int(quantity)
        csv = position.get_port_data()
        df = position.get_data_from_file(csv)
        df.loc[len(df.index)] = [ticker, 'Equity', '', '', quantity, '', '']
        df.sort_values(by=['Symbol'], inplace=True)
        position.save_user_port(df)
        group, deltas, vols = position.group_process(df, ticker)

app/templates/main/about.html
{% extends "main/main_base.html" %}

{% block content %}

     <div class="container-fluid p3">
     <div class="jumbotron">
          <h1 class="display-3">Just a bit about Risky!</h1>
          <p class="lead">We are development stage company working on bring world class risk tools to indvidual investors.  We see the huge growth in
                            option trading by individual investors as a permanent phenomenon but we know the tools provided by the retail brokareage houses
                            are inferior at best.  Our goal is to change that and arm indviduals with the same tools as the "professional" traders!</p>
          <hr class="my-4">
          <p>We welcome your feedback and ideas. Let us know what you like - what you don't like - and what you'd like to see us add!  We plan continuous roll outs as
             we develop new tools and enhance the exitising ones so check back regularly to see what is new!</p>

         <h4 class="text-info"> About Our Founder</h4>
          <p class="lead text-info"> Rob Prellwitz is a reformed hedge fund trader, having worked for Stark Investments from 1998 - 2014. Stark grew from less than
              $500 Million in AUM to $15 Billion in 2008.  He knows the tools and strategies used by the biggest and best players in the market and he is now
              dedicated to bring those tools and strategies to everyone.  This is the start of that journey!  Join us, it is going to be an amazing ride.
          </p>

         <p small class="text-danger"> Remember - Don't Pan!c and always remember your towel!</p>
        </div>

     </div>


    <div class="row">
        <div class="col-lg-4">
        </div>
    </div>

{% endblock %}

app/templates/main/admin_page.html
{% extends "main/main_base.html" %}  {# main/main_base.html extends layout.html #}

{% block content %}
    <h2>{%trans%}Admin Page{%endtrans%}</h2>
    <p><a href={{ url_for('user.register') }}>{%trans%}Register{%endtrans%}</a></p>
    <p><a href={{ url_for('user.login') }}>{%trans%}Sign in{%endtrans%}</a></p>
    <p><a href={{ url_for('main.home_page') }}>{%trans%}Home Page{%endtrans%}</a> (accessible to anyone)</p>
    <p><a href={{ url_for('main.member_page') }}>{%trans%}Member Page{%endtrans%}</a> (login_required: member@example.com / Password1)</p>
    <p><a href={{ url_for('main.admin_page') }}>{%trans%}Admin Page{%endtrans%}</a> (roles_required: admin@example.com / Password1)</p>
    <p><a href={{ url_for('user.logout') }}>{%trans%}Sign out{%endtrans%}</a></p>
{% endblock %}

app/templates/main/group.html
{% extends "main/main_base.html" %}  {# main/main_base.html extends layout.html #}

{% block pre_content %}

<div class="container-fluid p-2">
        <div class="row align-content-center">
            <div class="col-lg-3">
                <form class="form-inline my-2 my-lg-0 px-2" action="{{  url_for('main.group_page') }}" method="POST">
                    <input class="form-control mr-sm-2" type="text" name="ticker" placeholder="AAPL">
                    <button class="btn btn-info my-2 my-sm-0" type="submit" value="Search">Ticker ( Group )</button>
                </form>
            </div>
            <div class="col-lg-1">
                <form class="form-inline my-2 my-lg-0" action="{{  url_for('main.portfolio_page') }}" method="GET">
                    <button class="btn btn-info my-2 my-sm-0" type="submit" value="Search">Back to Portfolio</button>
                </form>
            </div>

            <div class="col-lg-2">
                <button class="btn btn-info" onclick="openForm()">Add New Equity</button>
                    <div class="form-popup" id="NewEquity">
                      <form action="{{  url_for('main.new_equity_page') }}"  method="POST" class="form-container">
                        <h4 class="text-info">New Equity</h4>

                        <label for="ticker" class="text-info"><b>Ticker</b></label>
                        <input type="text" placeholder="Ticker" name="ticker" required>

                        <label for="Quantity" class="number"><b>Quantity</b></label>
                        <input type="number" placeholder="Quantity" name="quantity" required>

                        <button type="submit" class="btn">Save</button>
                        <button type="submit" class="btn cancel" onclick="closeForm()">Close</button>
                      </form>
                    </div>
            </div>

             <div class="col-lg-2">
                <button class="btn btn-info" onclick="openForm1()">Add New Option</button>
                    <div class="form-popup" id="NewOption">
                      <form action="{{  url_for('main.new_option_page') }}"  method="POST" class="form-container">
                        <h4 class="text-info">New Option</h4>

                        <label for="symbol" class="text-info"><b>Symbol</b></label>
                        <input type="text" placeholder="Ticker" name="symbol" required>

                          <label for="underlying ticker" class="text-info"><b>Unerlying Ticker</b></label>
                        <input type="text" placeholder="Ticker" name="underlying" required>

                           <label for="Option Type" class="text-info"><b>CALL or PUT</b></label>
                        <input type="text" placeholder="CALL or PUT" name="type" required>

                        <label for="Quantity" class="text-info"><b>Quantity</b></label>
                        <input type="number" placeholder="Quantity" name="quantity" required>

                          <label for="Strike Price" class="text-info"><b>Strike Price</b></label>
                        <input type="number" placeholder="Strike Price" name="strike price" required>

                          <label for="Expiration" class="text-info"><b>Expiration Date</b></label>
                        <input type="text" placeholder="Expiration" name="expiration" required>

                        <button type="submit" class="btn">Save</button>
                        <button type="submit" class="btn cancel" onclick="closeForm1()">Close</button>
                      </form>
                    </div>
            </div>

        </div>
    </div>
<hr style="height: 4px; color: #007bff">
{% endblock %}

{% block content %}
 <div class="container-fluid">

    {% for table in tables %}
            <h3 class="text-info">
                 {{titles[loop.index]}}
            </h3>
        <div class="container-fluid p-3 my-3">
            {{ table | safe }}
        </div>

    {% endfor %}

 </div>

{% endblock %}

app/templates/main/holdings.html
{% extends "main/main_base.html" %}  {# main/main_base.html extends layout.html #}

{% block pre_content %}
{% endblock %}


{% block content %}
<table class="table table-responsive">
  <thead>
    <tr class="table-info">
      <th scope="col">Security</th>
        <th scope="col">Security Type</th>
      <th scope="col">Underlying Ticker</th>
      <th scope="col">Option Tupe</th>
      <th scope="col">Holding</th>
        <th scope="col">Strike</th>
        <th scope="col">Expiration</th>
        <th scope="col">Price</th>
        <th scope="col">Delta</th>
    </tr>
  </thead>

      <tbody>
      {%  for security_key, security in securities %}
        <tr class="table-primary" style="font-size:13px">
            <th scope="row">{{  security.symbol }}</th>
            <td>{{ security.type }}</td>
            <td>{{ security.underlying }} </td>
            <td>{{ security.optiontype }}</td>
            <td>{{ security.position }}</td>
            <td>{{security.strike}}</td>
            <td>{{ security.expiration }}</td>
            <td>$  {{ security.price }}</td>
            <td>{{ security.delta }} %</td>
        </tr>
      {% endfor %}
      </tbody>

</table>
{% endblock %}

app/templates/main/home_page.html
{% extends "main/main_base.html" %}  {# main/main_base.html extends layout.html #}

{% block content %}

{##}
{#    <p><a href={{ url_for('user.login') }}>{%trans%}Sign in{%endtrans%}</a></p>#}
{#    <p><a href={{ url_for('main.home_page') }}>{%trans%}Home Page{%endtrans%}</a> (accessible to anyone)</p>#}
{#    <p><a href={{ url_for('main.member_page') }}>{%trans%}Member Page{%endtrans%}</a> (login_required: member@example.com / Password1)</p>#}

    <div class="container-fluid p-10 my-5; align-content-center">
    <P>
        <h1 class="text-info"; align="center"> Welcome to Risky!   The individual investors secret weapon!</h1>
        <H3 class="text-warning"; align="center"> The tools professional investors use to manage risk now at your fingertips</H3>
        <h4 class="text-success"; align="center"> If you trade options in your brokerage account our tool is for you.  Try it and you won't go back!</h4>


    </P>

    </div>
    <div class="container-fluid p-10 my-lg-5">
        <div class="row align-content-center">
              <div class="col-lg-4">
               <img class="align-content-end" src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Long_call_option.svg/1200px-Long_call_option.svg.png" alt="42" width="250" height="200">
              </div>
          <div class="col-lg-4">
               <img class="align-content-end" src="https://www.fidelity.com/bin-public/060_www_fidelity_com/images/LC/ShortButterflyCalls_600x340.png" alt="42" width="250" height="200">
            </div>
          <div class="col-lg-4">
               <img class="align-content-end" src="https://www.danielstrading.com/wp-content/uploads/2013/05/futures-options-strategies_long-risk-reversal_960x680-300x213.png" alt="42" width="250" height="200">
            </div>
        </div>
    </div>




{% endblock %}

{% block pre_content %}

</nav>
{% endblock %}

app/templates/main/main_base.html
{% extends "layout.html" %}

app/templates/main/portfolio.html
{% extends "main/main_base.html" %}

{% block pre_content %}

    <div class="container-fluid p-3">
        <div class="row align-content-center">
            <div class="col-lg-3">
                <p class="text-info"> Use this group box to view Option positions in greater detail</p>
                <form class="form-inline my-2 my-lg-0" action="{{  url_for('main.group_page') }}" method="POST">
                    <input class="form-control mr-sm-2" type="text" name="ticker" placeholder="AAPL">
                    <button class="btn btn-info my-2 my-sm-0" type="submit" value="Search">Ticker ( Group )</button>
                </form>
            </div>

            <div class="col-lg-1">
                <form class="form-inline my-2 my-lg-0" action="{{  url_for('main.portfolio_page') }}" method="GET">
                    <button class="btn btn-info my-2 my-sm-0" type="submit" value="Search">Back to Portfolio</button>
                </form>
            </div>

            <div class="col-lg-2">
                <button class="btn btn-info" onclick="openForm()">Add New Equity</button>
                    <div class="form-popup" id="NewEquity">
                      <form action="{{  url_for('main.new_equity_page') }}"  method="POST" class="form-container">
                        <h4 class="text-info">New Equity</h4>

                        <label for="ticker" class="text-info"><b>Ticker</b></label>
                        <input type="text" placeholder="Ticker" name="ticker" required>

                        <label for="Quantity" class="number"><b>Quantity</b></label>
                        <input type="number" placeholder="Quantity" name="quantity" required>

                        <button type="submit" class="btn">Save</button>
                        <button type="submit" class="btn cancel" onclick="closeForm()">Close</button>
                      </form>
                    </div>
            </div>

             <div class="col-lg-2">
                <button class="btn btn-info" onclick="openForm1()">Add New Option</button>
                    <div class="form-popup" id="NewOption">
                      <form action="{{  url_for('main.new_option_page') }}"  method="POST" class="form-container">
                        <h4 class="text-info">New Option</h4>

                        <label for="symbol" class="text-info"><b>Symbol</b></label>
                        <input type="text" placeholder="Ticker" name="symbol" required>

                          <label for="underlying ticker" class="text-info"><b>Unerlying Ticker</b></label>
                        <input type="text" placeholder="Ticker" name="underlying" required>

                           <label for="Option Type" class="text-info"><b>CALL or PUT</b></label>
                        <input type="text" placeholder="CALL or PUT" name="type" required>

                        <label for="Quantity" class="text-info"><b>Quantity</b></label>
                        <input type="number" placeholder="Quantity" name="quantity" required>

                          <label for="Strike Price" class="text-info"><b>Strike Price</b></label>
                        <input type="number" placeholder="Strike Price" name="strike price" required>

                          <label for="Expiration" class="text-info"><b>Expiration Date</b></label>
                        <input type="text" placeholder="Expiration" name="expiration" required>

                        <button type="submit" class="btn">Save</button>
                        <button type="submit" class="btn cancel" onclick="closeForm1()">Close</button>
                      </form>
                    </div>
            </div>

        </div>
    </div>

{% endblock %}



{% block content %}
<div class="container-fluid p-5" align="content-center">
    <H2 style="color: #007bff"> Positions </H2>
        <table id="Portfolio" align="center">
            {% for table in tables %}
                <h4></h4>
            {{ table|safe }}
            {% endfor %}
        </table>

</div>
{% endblock %}

app/templates/main/sample.html
{% extends "layout.html" %}
{% block title %}Equity list{% endblock %}
{% block content %}
    <h1 class="title" style="color:SlateBlue">Equity Holdings</h1>


<form action ="" method = "post" name = "equity_list">
    <table class="table is-flex is-striped is-fullwidth is-align-content-center">
        <div style="bgcolor:gray; color:SlateBlue">
        <th >Ticker </th>
        <th>Name </th>
            <th>  Holdings  </th>
        </div>
      {% for equity_key, equity in equities %}
      <tr>
            <td>
                <label class="checkbox">
                    <input type = "checkbox" name = "equity_keys" value = "{{ equity_key }}"/>
                </label>
                <a>{{ equity.ticker }}</a>
            </td>
            <td> {{ equity.name }}</td>
            <td>{{ equity.shares }}</td>
      </tr>
      {% endfor %}
    </table>

    <div class="field is-grouped">
        <div class="control">
          <button class="button is-danger is-small">Delete</button>
        </div>
      </div>

</form>
{% endblock %}

app/templates/main/sample2.html
{% extends "main/main_base.html" %}

{% block pre_content %}
{% endblock %}
<div class="container-fluid p-4">
{% block content %}
<div class="container-fluid p-4">
    <div style="align-content: stretch ">
    <H2 style="align-content: center; color: dodgerblue"> Sample Position Data </H2>
    </div>
{#    {% for page in pages %}#}
{#        {{ page|safe }}#}
{#    {% endfor %}#}
    <p class="text-info">  This is a simple sample view.  Please sign up for a free account to see the full power of Risky!</p>
        <table>
            {% for table in tables %}
                <h4></h4>
            {{ table|safe }}
            {% endfor %}
        </table>
</div>

{% endblock %}

</div>

app/templates/main/user_page.html
{% extends "main/main_base.html" %}  {# main/main_base.html extends layout.html #}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light px-2">
            <a class="navbar-brand" href="#"> User Tools </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor03">
                <ul class="navbar-nav mr-auto">


                    <form class ="px-3" action="" method="POST" enctype="multipart/form-data">
                        <p id="fileHelp" class="form-text text-danger">Use this to upload updates to your user created portfolio</p>
                         <div class="form-group">
                            <div class="input-group mb-3" >
                              <div class="custom-file">
                                <input type="file" class="custom-file-input text-warning" name="userport" id="userport">
                                <label class="custom-file-label text-danger" for="userport">Choose CSV</label>
                              </div>
                              <div class="input-group-append">
                                  <button class="input-group-text text-info" type="submit">Upload</button>
                              </div>
                            </div>
                         </div>
                    </form>

                    <form class="px-3" action="" method="POST" enctype="multipart/form-data">
                        <p id="fileHelp" class="form-text text-danger">Use this to upload updates to your E*Trade portfolio</p>
                         <div class="form-group">
                            <div class="input-group mb-3" >
                              <div class="custom-file">
                                <input type="file" class="custom-file-input text-warning" name="etradeport" id="etradeport">
                                <label class="custom-file-label text-danger" for="etradeport">Choose Etrade CSV</label>
                              </div>
                              <div class="input-group-append">
                                  <button class="input-group-text text-info" type="submit">Upload</button>
                              </div>
                            </div>
                         </div>
                    </form>

                    <li class="nav-item p-lg-4">
                      <a class="navbar-brand text-info"  href="{{  url_for('main.portfolio_page') }}"> Load Portfolio </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                    </ul>
            </div>
</nav>

    <div class="container-fluid p3">
    <div class="row">
        <div class="col-lg-4">
            <div class="card text-white bg-primary mb-3" style="max-width: 50rem;">
              <div class="card-header"> Standard CSV Instructions </div>
              <div class="card-body">
                <h4 class="card-title">User Portfolio file details</h4>
                <p class="card-text">Getting your portfolio loaded is simple.  You need a csv file of your positions in the following format:<br>
                     Header row: <br> Symbol, Type, Option Underlier,Option Type, Quantity, Strike Price, Expiration Date <br>
                    The body is one security per row with the relevant data (obviously equities have less content!)<br>
                     equity example:  F,Equity,--,--,2000,--,--<br>
                     option example:  F Feb 05 '21 $12 Call,Option,F,CALL,30,12,2/5/2021</p>
              </div>
            </div>
        </div>

        <div class="col-lg-4">
            <div class="card text-white bg-primary mb-4" style="max-width: 50rem;">
              <div class="card-header">Etrade Instructions</div>
              <div class="card-body">
                <h4 class="card-title">Etrade File Details </h4>
                <p class="card-text">Etrade users simply need to download a csv file from Etrade with the fields in the order shown below.  Thats it!
                                        We will take care of the rest! <br>  Fields Required: <br>
                                         Symbol, Type, Option Underlier,Option Type, Quantity, Strike Price, Expiration Date </p>
              </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="card text-white bg-info mb-3" style="max-width: 20rem;">
              <div class="card-header">Attention</div>
              <div class="card-body">
                <h4 class="card-title">Please Check Back</h4>
                <p class="card-text">We intend to add other retail broker support regularly.  Let us know your favorite so we
                                     know who to focus on and check back often to see if we have added yours!</p>
              </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

{% block post_content %}
<table class="table table-responsive">
  <thead>
    <tr class="table-info">
        <th scope="col">Security</th>
        <th scope="col">Group</th>
        <th scope="col">type</th>
        <th scope="col">Underlying</th>
        <th scope="col">Holding</th>
        <th scope="col">Price</th>
        <th scope="col">Delta</th>
        <th scope="col">Exposure</th>
        <th scope="col">Dollar Exposure</th>
    </tr>
  </thead>
  <tbody>
    <tr class="table-primary">
        <th scope="row">Active</th>
        <td>Rob</td>
        <td>Prellwitz</td>
        <td>Don't</td>
        <td>Panic</td>
        <td>The </td>
        <td>Answer </td>
        <td>is </td>
        <td>42 !</td>

    </tr>
  </tbody>
</table>
{% endblock %}