app/views/main_views.py
from flask import Blueprint, redirect, render_template, current_app, request, url_for, flash
from flask_user import current_user, login_required, roles_required
from app import db
from app.models.user_models import UserProfileForm
from app.securities.holdings import Security_Data
from app.securities.data import Position
import pandas
import os
from datetime import datetime
main_blueprint = Blueprint('main', __name__, template_folder='templates')


# The Home page is accessible to anyone
@main_blueprint.route('/')
def home_page():
    return render_template('main/home_page.html')

@main_blueprint.route('/about')
def about_page():
    return render_template('main/about.html')


@main_blueprint.route('/login', methods=['GET', 'POST'])
def sign_in_page():
    return render_template('main/user_login.html')


# The User page is accessible to authenticated users (users that have logged in)
@main_blueprint.route('/member', methods=['GET', 'POST'])
@login_required  # Limits access to authenticated users
def member_page():
    if request.method == "POST" and 'userport' in request.files:
        position = Position()
        email = current_user.email
        file = request.files['userport']
        file.save(os.path.join('app/static/portfolios', email))
        flash("File Saved!")
        return render_template('main/user_page.html')
    if request.method == "POST" and 'etradeport' in request.files:
        position = Position()
        email = current_user.email
        file = request.files['etradeport']
        file = position.get_etrade_data_from_file(file)
        file.to_csv(os.path.join('app/static/portfolios', email), encoding='utf-8', index=False)
        flash("File Saved!")
        return render_template('main/user_page.html')
    else:
        return render_template('main/user_page.html')


# The Admin page is accessible to users with the 'admin' role
@main_blueprint.route('/admin')
@roles_required('admin')  # Limits access to users with the 'admin' role
def admin_page():
    return render_template('main/admin_page.html')


@main_blueprint.route('/main/profile', methods=['GET', 'POST'])
@login_required
def user_profile_page():
    # Initialize form
    form = UserProfileForm(request.form, obj=current_user)

    # Process valid POST
    if request.method == 'POST' and form.validate():
        # Copy form fields to user_profile fields
        form.populate_obj(current_user)

        # Save user_profile
        db.session.commit()

        # Redirect to home page
        return redirect(url_for('main.home_page'))

    # Process GET or invalid POST
    return render_template('main/user_profile_page.html',
                           form=form)


@main_blueprint.route('/equity')
@login_required
def equity_page(equity_key):
    eqdb = current_app.config["eqdb"]
    equity = eqdb.get_equity(equity_key)
    return render_template("equity.html", equity=equity)


# @main_blueprint.route('/holdings', methods=['GET', 'POST'])
# @login_required
# def holdings_page():
#     secdb = Security_Data()
#     holdings = secdb.get_holdings('holdings2.csv')
#     data = secdb.get_data(holdings)
#     dataII = data.to_numpy()
#     secdb = secdb.seed_holdings(dataII)
#     if request.method == "GET":
#         securities = secdb.get_securities()
#         return render_template("main/holdings.html", securities=securities)
#     else:
#         form_security_keys = request.form.getlist("security_keys")
#         for form_security_key in form_security_keys:
#             secdb.delete_equity(int(form_security_key))
#         return redirect(url_for("holdings_page"))


@main_blueprint.route('/Portfolio', methods=['GET', 'POST'])
@login_required
def portfolio_page():
    if request.method == "GET":
        position = Position()
        csv = position.get_port_data()
        df = position.get_data_from_file(csv)
        holdings = position.get_holdings(df)
        return render_template("main/portfolio.html", tables=[
            holdings.to_html(header=True, index=False, na_rep="--", table_id="Portfolio",
                             columns=['Symbol', 'Option Underlier',
                                      'Option Type', 'Quantity', 'Strike Price', 'Expiration Date', 'Market Price',
                                      'Option Delta', 'Exposure'],
                             formatters={"Market Price": "${:,.2f}".format, "Option Delta": "{:.1%}".format,
                                         "Exposure": "{:,.0f}".format})])
    elif request.method == "POST":

        position = Position()
        email = current_user.email
        file = request.files['userport']
        file.save(os.path.join('app/static/portfolios', email))
        portfolio = 'app/static/portfolios/' + str(email)
        df = position.get_data_from_file(portfolio)
        holdings = position.get_holdings(df)
        return render_template("main/portfolio.html", tables=[
            holdings.to_html(header=True, index=False, na_rep="--", table_id="Portfolio",
                             columns=['Symbol', 'Option Underlier',
                                      'Option Type', 'Quantity', 'Strike Price', 'Expiration Date',
                                      'Market Price',
                                      'Option Delta', 'Exposure'],
                             formatters={"Market Price": "${:,.2f}".format, "Option Delta": "{:.1%}".format,
                                         "Exposure": "{:,.0f}".format})])

    else:
        flash("Something went wrong - you were redirected home!  Please try again.")
        return redirect(url_for("main.member_page"))


@main_blueprint.route('/Group', methods=['GET', 'POST'])
@login_required
# @csrf.exempt
def group_page():
    # if request.method == "GET":
    #     position = Position()
    #     ticker = "AAPL"
    #     csv = position.get_port_data()
    #     df = position.get_data_from_file(csv)
    #     df["Option Underlier"] = df.apply(lambda x: position.add_und(x["Type"], x["Option Underlier"], x["Symbol"]),
    #                                       axis=1)
    #     group = position.filter_holdings(df, ticker)
    #     group = position.get_holdings(group)
    #     group.loc["Total Exposure"] = group.sum(["Exposure"],axis =0)
    #     return render_template("main/group.html", tables=[
    #         group.to_html(header=True, index=False, na_rep="--", table_id="Portfolio",
    #                       columns=['Symbol', 'Option Underlier',
    #                                'Option Type', 'Quantity', 'Strike Price', 'Expiration Date', 'Market Price',
    #                                'Option Delta', 'Exposure'],
    #                       formatters={"Market Price": "${:,.2f}".format, "Option Delta": "{:.1%}".format,
    #                                   "Exposure": "{:,.0f}".format})])
    if request.method == "POST":
        position = Position()
        ticker = request.form.get('ticker').upper()
        csv = position.get_port_data()
        df = position.get_data_from_file(csv)
        group, deltas, vols = position.group_process(df, ticker)
        vol_exp = position.vols_process(vols)
        exposure = position.delta_process(deltas)
        return render_template("main/group.html", tables=[group, exposure, vol_exp], titles=['', 'Group Holdings', 'Equity Exposure', 'Volatility Exposure'])
    else:
        flash("Something went wrong - you were redirected home!  Please try again.")
        return redirect(url_for("main.member_page"))


@main_blueprint.route('/Sample2', methods=['GET', 'POST'])
def sample2_page():
    if request.method == "GET":
        position = Position()
        csv = "holdings2.csv"
        df = position.get_etrade_data_from_file(csv)
        sample2 = position.get_holdings(df)
        return render_template("main/sample2.html", tables=[
            sample2.to_html(header=True, index=False, na_rep="--", table_id="Portfolio",
                            columns=['Symbol', 'Option Underlier',
                                     'Option Type', 'Quantity', 'Strike Price', 'Expiration Date', 'Market Price',
                                     'Option Delta', 'Exposure'],
                            formatters={"Market Price": "${:,.2f}".format, "Option Delta": "{:.1%}".format,
                                        "Exposure": "{:,.0f}".format})])
    else:
        return redirect(url_for("main/home_page.html"))

@main_blueprint.route('/NewEquity', methods=['GET', 'POST'])
@login_required
# @csrf.exempt
def new_equity_page():
    # if request.method == "GET":
    #     position = Position()
    #     ticker = "FSLY"
    #     csv = position.get_port_data()
    #     df = position.get_data_from_file(csv)
    #     group = position.filter_holdings(df, ticker)
    #     group = position.get_holdings(group)
    #     group.loc["Total Exposure"] = group.sum(["Exposure"],axis =0)
    #     return render_template("main/group.html", tables=[
    #         group.to_html(header=True, index=False, na_rep="--", table_id="Portfolio",
    #                       columns=['Symbol', 'Option Underlier',
    #                                'Option Type', 'Quantity', 'Strike Price', 'Expiration Date', 'Market Price',
    #                                'Option Delta', 'Exposure'],
    #                       formatters={"Market Price": "${:,.2f}".format, "Option Delta": "{:.1%}".format,
    #                                   "Exposure": "{:,.0f}".format})])
    if request.method == "POST":
        position = Position()
        ticker = request.form.get('ticker').upper()
        quantity = request.form.get("quantity")
        quantity = int(quantity)
        csv = position.get_port_data()
        df = position.get_data_from_file(csv)
        df.loc[len(df.index)] = [ticker, 'Equity', '', '', quantity, '', '']
        df.sort_values(by=['Symbol'], inplace=True)
        position.save_user_port(df)
        group, deltas, vols = position.group_process(df, ticker)

app/templates/flask_user_layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ user_manager.USER_APP_NAME }}</title>

    <!-- Bootstrap -->
    <link href="{{ url_for('static', filename='bootstrap/css/slate.css') }}" rel="stylesheet">

    <!-- In-lining styles to avoid needing a separate .css file -->
    <style>
        hr { border-color: #cccccc; margin: 0; }
        .no-margins { margin: 0px; }
        .with-margins { margin: 10px; }
        .col-centered { float: none; margin: 0 auto; }
    </style>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.js"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js"></script>
    <![endif]-->

    {# *** Allow sub-templates to insert extra html to the head section *** #}
    {% block extra_css %}{% endblock %}
  </head>


<body>
    {% block body %}
    <div id="header-div" class="clearfix with-margins">
        <div class="pull-left"><a href="/"><h1 class="no-margins">{{ user_manager.USER_APP_NAME }}</h1></a></div>
        <div class="pull-right">
            {% if call_or_get(current_user.is_authenticated) %}
                <a href="{{ url_for('user.edit_user_profile') }}">{{ current_user.username or current_user.email }}</a>
                &nbsp; | &nbsp;
                <a href="{{ url_for('user.logout') }}">{%trans%}Sign out{%endtrans%}</a>
            {% else %}
                <a href="{{ url_for('user.login') }}">{%trans%}Sign in{%endtrans%}</a>
            {% endif %}
        </div>
    </div>
    {% block menu %}
    <div id="menu-div" class="with-margins">
        <a href="/">{%trans%}Home page{%endtrans%}</a>
    </div>
    {% endblock %}
    <hr class="no-margins"/>

    <div id="main-div" class="with-margins">
    {# One-time system messages called Flash messages #}
    {% block flash_messages %}
        {%- with messages = get_flashed_messages(with_categories=true) -%}
            {% if messages %}
                {% for category, message in messages %}
                    {% if category=='error' %}
                        {% set category='danger' %}
                    {% endif %}
                    <div class="alert alert-{{category}}">{{ message|safe }}</div>
                {% endfor %}
            {% endif %}
        {%- endwith %}
    {% endblock %}

    {% block main %}
        {% block content %}{% endblock %}
    {% endblock %}
    </div>

    <br/>
    <hr class="no-margins"/>
    <div id="footer-div" class="clearfix with-margins">
        <div class="pull-left">{{ user_manager.USER_APP_NAME }} {{ user_manager.USER_APP_VERSION }}</div>
        <div class="pull-right">&copy; {{ user_manager.USER_COPYRIGHT_YEAR }} {{ user_manager.USER_CORPORATION_NAME }}</div>
    </div>
    {% endblock %}


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <!-- Bootstrap -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

    {# *** Allow sub-templates to insert extra html to the bottom of the body *** #}
    {% block extra_js %}{% endblock %}

  </body>
</html>

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- These 3 meta tags MUST come first -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- These 3 meta tags MUST come first -->
        <title>Don't Panic !</title>
        <!-- Bootstrap CSS and JS -->
{#        <link href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">#}
        <link href="{{ url_for('static', filename='bootstrap/css/darkly.css') }}" rel="stylesheet">
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="{{ url_for('static', filename='bootstrap/js/html5shiv.min.js') }}"></script>
            <script src="{{ url_for('static', filename='bootstrap/js/respond.min.js') }}"></script>
        <![endif]-->

        <!-- Application specific CSS-->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css') }}">

         <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" href="{{ url_for('main.home_page') }}"> RISKY! </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor02">
                <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href={{ url_for('user.register') }}>Register
                    <span class="sr-only">(current)</span>
                    </a>
                </li>
                  <li class="nav-item">
                    <a class="nav-link" href={{ url_for('user.login') }}>  Sign In  </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.sample2_page')}}">  Sample View  </a>
                  </li>
{#                  <li class="nav-item">#}
{#                    <a class="nav-link" href="{{  url_for('main.portfolio_page') }}">Portfolio</a>#}
{#                    <li class="nav-item">#}
                    <li>
                        <a class="nav-link" href={{ url_for('main.member_page') }}>  Member Page  </a>
                    </li>

                    <a class="nav-link" href="{{ url_for('main.about_page') }}">About</a>
                </ul>
            </div>
             <div class="pull-right" align="right">
                {% if current_user.is_authenticated %}

                    <a href="{{ url_for('main.user_profile_page') }}">{{ current_user.first_name or current_user.username or current_user.email }}</a>
                    &nbsp; | &nbsp;
                    <a href="{{ url_for('user.logout') }}">Sign out</a>
                {% else %}
                    <a href="{{ url_for('user.login') }}">Sign in</a>
                {% endif %}
            </div>
         </nav>
    </head>
    <body>
        {% block body %}
        <!-- Application specific HTML -->

        {% block pre_content %}{% endblock %}

        {# One-time system messages called Flash messages #}
        {% block flash_messages %}
            {%- with messages = get_flashed_messages(with_categories=true) -%}
                {% if messages %}
                    {% for category, message in messages %}
                        {% if category=='error' %}
                            {% set category='danger' %}
                        {% endif %}
                        <div class="alert alert-{{category}}">{{ message|safe }}</div>
                    {% endfor %}
                {% endif %}
            {%- endwith %}
        {% endblock %}

        {% block content %}{% endblock %}

        {% block post_content %}{% endblock %}
        </div>

        <br/>
        <hr class="no-margins"/>

<div id="footer-div" class="container-fluid p-5">
    <div class="row align-content-center">
      <div class="col-lg-4">
          <div class="card border-light mb-3" style="max-width: 18rem;">
                  <div class="card-header text-warning">Don't Pan!c Inc.</div>
                      <div class="card-body">
                        <h5 class="card-title text-danger">Contact Info</h5>
                        <p class="card-text text-info">reprisk@gmail.com</p>
                  </div>
          </div>
      </div>
      <div class="col-lg-4">
          <div class="text-danger"; align="content-center">&copy; 2021 Don't Panic!</div>
          <div class="text-danger"; align="content-center">{{ user_manager.app_name }} v1.42</div>
      </div>
      <div class="col-lg-4">
           <img align="content-end"; src="https://ritholtz.com/wp-content/uploads/2020/03/dontpanic.jpg" alt="42" width="50" height="35">
      </div>
    </div>

            <!-- Application specific HTML -->

        <hr class="no-margins"/>

        <div id="main-div" class="with-margins">


        <!-- Bootstrap JS -->
        <script src="{{ url_for('static', filename='bootstrap/js/jquery.min.js') }}"></script>
        <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='bootstrap/js/risk.js') }}"></script>
        <!-- Optional Google Analytics: change UA-XXXXX-X to be your site's ID.
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='https://www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
        -->

        </div>
        {% endblock %}
    </body>
</html>